name: Run github.py and Upload to uploads/ (with timestamp and failure recovery)

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies (optional)
      run: pip install -r requirements.txt || true

    - name: Run github.py
      run: python github.py

    - name: Move result to uploads with timestamp
      run: |
        mkdir -p uploads
        timestamp=$(date +'%Y-%m-%d_%H-%M-%S')
        if [ -f available.txt ]; then
          mv available.txt "uploads/$timestamp.txt"
        else
          echo "⚠️ 没有找到 available.txt，跳过移动"
        fi

    - name: Commit and push if success
      if: success()
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add uploads/
        git commit -m "✅ Output uploaded on successful run"
        git push
      continue-on-error: true

    - name: Try to commit and push if script failed
      if: failure()
      run: |
        echo "❌ 脚本执行失败，尝试上传部分结果..."
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add uploads/
        git commit -m "⚠️ Partial output uploaded after failure"
        git push
      continue-on-error: true
