name: Run github.py and Upload to uploads/

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies (optional)
      run: pip install -r requirements.txt || true

    - name: Run github.py script
      run: python github.py

    - name: Move output file to uploads/
      run: |
        mkdir -p uploads
        mv available.txt uploads/available.txt || echo "No available.txt to move"

    - name: Commit and push uploads folder
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add uploads/
        git commit -m "Auto upload: output moved to uploads/"
        git push
      continue-on-error: true
