name: Run GitHub

on:
  workflow_dispatch:  # 手动触发

jobs:
  github:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true
        pip install requests wordfreq beautifulsoup4 lxml html5lib nltk tqdm

    - name: Run github.py
      run: |
        python github.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: github-results
        path: ./*.txt   # 上传根目录所有 txt 文件
